### ISSUE TITLE
API dead?

### ISSUE THREAD

**Issue by benlower** [PredictTheSky/predictthesky.github.io#1]
Found this over at https://data.nasa.gov/developer.  None of the routes outlined at http://predictthesky.org/developers.html seem to work.  Is the API dead or has it moved?

**Comment by nickcharlton** [comment]
The project isn't dead (we've been working on the library that now backs it), but the API bit currently is.

I've been meaning to update the site to make it a bit clearer. It's been a bit on hold for the past year or so — the perennial problem of projects started at hack days.

This organisation really represents a bit refactoring of what we'd originally hoped to come out with, and I'm pretty sure the old thrown together one isn't online any more.

**Comment by isaachinman** [comment]
@nickcharlton Do you know of any APIs that provide similar data? Otherwise, can you let me know where you pulled info for current weather and current astral bodies overhead a lat/long? Not even sure if this API is necessary if those two conditions are supported by other APIs.

**Comment by cowboysdude** [comment]
Yeah this api is pretty much dead......

**Comment by nickcharlton** [comment]
I would, at this point, agree that it's dead.

If people would like to open PRs, I'd be happy to review them and then add you to the organisation. I'm not aware of anything similar, either.

**Comment by isaachinman** [comment]
@nickcharlton I would definitely be willing to maintain this repo. What is needed? The last commit to master was 5 years ago. Let me know where to start.

**Comment by nickcharlton** [comment]
Yay!

I suspect the first step would be to get going with `spacebodies` and start seeing what's missing for using it to build up API responses.

Then, I'd look at building out some sort of API, with [Flask](http://flask.pocoo.org) perhaps? That starts to mirror what's shown on the site (this repo).

Opening issues is probably the best way to trigger discussions about things, and I'm more than happy to review any PRs. I'll add you to the organisation, too.
